kube-prometheus-stack:
  grafana:
    enabled: true
    admin:
      existingSecret: grafana-admin-secret
      userKey: admin-user
      passwordKey: admin-password
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://logging-loki.logging.svc.cluster.local:3100
        access: proxy
        isDefault: false
        jsonData:
          maxLines: 1000
          derivedFields: []
          lokiLogs:
            enable: true
          logVolumeEnabled: false
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-wildcard
      hosts:
        - grafana.chitra.doe24.chas-lab.dev
      tls:
        - secretName: grafana-tls
          hosts:
            - "*.chitra.doe24.chas-lab.dev"
  prometheus:
    prometheusSpec:
      retention: 15d
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 2Gi
  alertmanager:
    config:
      global:
        resolve_timeout: 5m
        smtp_smarthost: smtp.gmail.com:587
        smtp_from: chitra.inspires@gmail.com
        smtp_auth_username: chitra.inspires@gmail.com
        smtp_auth_password_file: /etc/alertmanager/secrets/alertmanager-gmail-config/alertmanager.yaml
        smtp_require_tls: true
      route:
        group_by: [alertname, namespace]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        receiver: gmail
        routes:
          - receiver: "null"
            matchers:
              - alertname = "Watchdog"
      receivers:
        - name: "null"
        - name: gmail
          email_configs:
            - to: chitra.inspires@gmail.com
              send_resolved: true
      inhibit_rules:
        - source_matchers:
            - severity = critical
          target_matchers:
            - severity =~ warning|info
          equal: [namespace, alertname]
    alertmanagerSpec:
      alertmanagerConfigSecret: alertmanager-gmail-config
      secrets:
        - alertmanager-gmail-config
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeProxy:
    enabled: false
  defaultRules:
    rules:
      etcd: false
      kubeScheduler: false
  prometheus-node-exporter:
    tolerations:
      - operator: Exists
