---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: acmedns-account
  namespace: cert-manager
spec:
  encryptedData:
    acmedns.json: AgBupHqugh/IUN3uYjWYS+yfpf0NThycsJfmV0bNkWllSM8u1tmPJwXtgAtcLA92Tnpp/4xnQ1iYoe5k1KC5nkkByGq8el8X3xMkdQd6DJn+SoGYrTJjkiIvb4XRj1UnQbnPMfTpgnHQmpqqt/sgvJhx6diQ2b12HwYsKQyLpV3emgzZsTtI7XSD2/FEmLDlWynL1jzNXcfMf2CapEk/K1I4zcX2UnFh2dEqfylxeApF9ROYwZ0YELk+UacJb382KGmcr8mTPkFYNGXpUpvaIlVbUv83RjcxAaiWfjtHXj5Vm13PLAf4lZ6E4AcDdx7v2M6u4aIc1Nd6q9A1gX2OtX7gITusIQRCFBh/EhR3ALQO+GmWBj7YcSTVJh7n71HFSeUO27NfdzOv0hr3C1ZCj22BMrsK09uFDImHf8+FUL/8ryzukPyasmSXHAHc3UjC1/P+G2wh//Q5hf+BKEP/DOZPhMWT0q34yeC3iABQhFF6YXXy7gE7naN7PUf4EPe5nJjsbK1ipqB7931/Tssy9bZfnsmBGN2+kXtSbCK2gN8RPWWzMCXkQP0R38Qk3palmF9eYLOGARp+jFhtcIyNgup9YdkUj7YXaeoSGaMAEeU1BXGaw0pguirYWZALF7CJ33hVNS4IRk2eMzDctXfJ3LA0ao449PU4nPrOBYtvOoeXwyYkb37k/XCz5praOLcQR/JeZD2T/WRZkdREuDUYLmkCRFc/JIaqXMZVCVnjsyKoYxyQkIaxrM2XYVYJk8Pa0bOZoaz6xgjF2/4qKraCIMk/Tfv9fIN9DP/spAT0NuNrc8F+M5GGtEjQ65rlWXnNCc1mxrtSSmSdHzWSIFEw0mbuZTB09azfFTWL9uvLW5LK51ilkM+NDrIxBMiCoG2e/UDNnZzbpQMkT68rj7/tjMl4eWzYsbpwaHHuywiXx0Rql6AEYVqyuU5dwc1baS4RbpuNgF4eqWQQyvyHZm9He2fZyv3zM8ojMkUrbidIukaHyjD+hf1LzPBFiPAOSt3wvNN4n8TTeDR+w12de9bZ/NdeUK4ITtsKyPszgW7t2ok=
  template:
    metadata:
      name: acmedns-account
      namespace: cert-manager
