---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: acmedns-account
  namespace: cert-manager
spec:
  encryptedData:
    acmedns.json: AgBAXL/rmHpsqypEUTXVEtaAoLJF77TtgCu9cJOEtLcUd+8TK6NjPpJbl3hx72DiJogfzxRnaXfrUIuRYgUEJe9WYrHYp2qSqYCk8NXlBmYrzmuStj4xV541EJJFJhC6n/MClQIpn3QaSujuZAWSBGqvddDOcl8JyajeW+WWF75Wc34dhIQTBDkJGoxskuxAl84x8a4/1qa53uTOFklxXHpquRX/o4X6/ajPMNGJdOPIc3rAmIY/nlEloKjsPG0PLnUQ6lp2kugbvmSzl0dkDdKRLCLv750BSfvOye7dINcK6JOA3QO86dSY80PpkwKKq0VbY7/u/7ZQuBjveEkDF1l7vBzliaF905Pi+3NAs8hiYAOwD4LtKQOuGP10bA0z/UwzQwDPlheGq+USCDjTOHhwIABRZxTC073x2Mjw7UHcn+3Bw/KNcrpJzCCKVHMLAvYfd+v04K7vpeeP4lKl4GzlwiWux+3/LNvsgfsUV1zmKl07yo+Hk+gpTAq6k/0Yu4vKuBtUoyDaX2AAE9Nq6SJIiKwscVBIYpX8puIU1iihsUqdUhsVMYNuFwsRGRZrDiJNmjWyLlZPSX+1rgJ46WW97XzVZqHkAhHSK+JkovcAKdsPXeIndNuIbXUcC4CKeCVDcj8y4tWXCWlty5Ny5U8SKDEp7neIQGHRq4DEtpASAfP6z5WNhFj12LtWJS41Q0AEEQI1vrsP70nNNiq//adIdxTy73joAktIcRepnVqEfWMsULTglw5DPWo4wZObj3Du315JO35xX0vF44w7N4d64ft1zMBp9nBw/Dz7jK1u/5fg1aCH3geFb/LLaWXyq8WSsyCh3HX7zIRBwkqxJeUwnZanb6osoF/iSvitW2xnRj0Gt+x0knCTJaj1vaUaVsaENUvOoiGLlvdNiZWFA6sNN+ePBQzZXF0MFqJCvDo81g1w0fG3TBvwAUwUEQiQXu1wSqu9R8iOQgtmnI2csFrnDBPI2Fw1W3FunvdUz+eGxzJXjsWtXomhKwZGuW2PqaUbXiC0FeDwkV4421P28MhIx4j/MU0=
  template:
    metadata:
      name: acmedns-account
      namespace: cert-manager
