---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-chasacademy
  namespace: chitra-plan-it
spec:
  encryptedData:
    .dockerconfigjson: AgAA0RTPBlLlTUQ0NQHqSh0N0BKS4N6eOJauZtM+LFHABR7zNDctA6APPh1/Ei33WU5LSXRpgAxezGk+4V4bTXOjJfc9C04nhZ95VyxrZ7zc+TW8oz2M2JUxfXVdN79DH3cPU7XrvuOsCyYul3ByFUHk5kWySc89qERK16thYoXtc6bsqEEPKbMHxhJem/6XvwAh8aY1i7SVjt5UoPfqrTat/Kt9Km2YUitNT8PFK9bT+3Klr4dIIXK9S5R5niBGNM8en5PUKJVvfo1/66KJUimco8UGT1fnVsFpp9Eli+QEnAyCp6byoZXwzylT6yok9FEl5c3i3tOjtTVOr44rI79Uu0D1V0y3AbiRBY13nh+WI7bLKV3UkAXZ7DzFU1KCcJwaGLuJ1W7O3BS55SKV+SzeDCSv+mF5HEX9Fav7Q1jN8qj2q6VH0L0wqqhoxSPNfdbXwNGOlcI1JkLLD/uWMXayGC6M9COU+M9ZvXW/EuIiQ80L1gLMu0O8CvrWo9YBUmYWs8r7gL0na+FUv/kE2R590E5pSwVkBej1Cm+Enc2qWFKNccV0XEwtmdsWGZCB45Y1HOQjSUCvqDJ5E8sGVn4CGpREJRQ+AzsOEckP9OX1as2rqt4/Z5T/Om+UEFKOZ5mr3/XWYE0C/jW1wD0es095XODqt8n6koIpdcAkRCqRP/pWt+CQ0gT3S5WxfUt2dhUNhq1ciBzQq8FVJEfg/skdInsBnyog3Q+SPEYFa8YIYnxko3pS7akP9K2ZF83VReped1kR/JL+7yPD8XyUkUwyrn5Bld0el226oGVdmmjVWTrXGu3n6FNxIoSL20aW72xlSign1Ml80LrkfYdTPEGjz8gMm38bJr5yRtazxaFaR1tv1M7w2MYHr15fFWRE+0Yvv1dMdXTkUib4pTvxjv5Vq6mgC/Lo+iiUhKyvfoTy8X70HCZDQoYqYbWvcz8=
  template:
    metadata:
      name: registry-chasacademy
      namespace: chitra-plan-it
    type: kubernetes.io/dockerconfigjson
