apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plan-it.fullname" . }}-database
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "plan-it.labels" . | nindent 4 }}
    component: database
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      {{- include "plan-it.selectorLabels" . | nindent 6 }}
      component: database
  template:
    metadata:
      labels:
        {{- include "plan-it.selectorLabels" . | nindent 8 }}
        component: database
    spec:
      containers:
        - name: sqlserver
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          ports:
            - name: mssql
              containerPort: {{ .Values.database.service.targetPort }}
              protocol: TCP
          env:
            - name: ACCEPT_EULA
              value: {{ .Values.database.env.ACCEPT_EULA | quote }}
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chitra-plan-it-app-secrets
                  key: saPassword
            - name: MSSQL_PID
              value: "Express"
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
          resources:
            {{- toYaml .Values.database.resources | nindent 12 }}
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: {{ include "plan-it.fullname" . }}-database-pvc
