{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "plan-it.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "plan-it.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- if eq (default "frontend" .service) "backend" }}
                name: {{ include "plan-it.fullname" $ }}-backend
                port:
                  number: {{ $.Values.backend.service.port }}
                {{- else }}
                name: {{ include "plan-it.fullname" $ }}-frontend
                port:
                  number: {{ $.Values.frontend.service.port }}
                {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
