{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "plan-it-database-secret",
    "namespace": "plan-it"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "plan-it-database-secret",
        "namespace": "plan-it"
      }
    },
    "encryptedData": {
      "SA_PASSWORD": "AgC0IKDB0kZtB3UoA5n7GUXAV3vehsyBub/f0wRMHQiZdTqtuQbqHE2RBu1/Yay58ahEKTVT0surXsEQBAx8xGRG7VNO3h/wID+hbwlygxIPgDy487hSuQZKG0Ns7+XJhUb6UXp9nyB8cgKYfoworBY8JjQFPNJHZ9DaLr9JzLKxo12hH0Dh8StgS2Jj6I/BeJsT5qB14pbnOShqjkgbn49vSmlpeoqluhH4Y8tQHVYQkH62aOQRY9yT631W+GmURlwUsM7paNI7+lNJuoQ85vz+TcK3j8dUrBY2+WmO5Wmqf+Bg7xC++MhEzmLGpL/XDqJz3oQh+rlJrVuG/aQrllBOZBSmlKIriFMBd7X/0txePfSnvkiUJHwR/ic72EMntZGUxpLCLAK/mb7+e7IVIxByFPlYbs5v9EIQqs8ZPbB5AegxkEwwKHbgfz6fgltUMjJXAHqMgiFt8xvlhb6PIgtafEOUjtKrn6Y/a/nkyX2l1cp5M9+HA/Ea3NrqVYin3osP4+uvDkL4xaIATN5/l1d5PnI5KI/Zjz7W+wCoev5pUbUIPFKkj41+8aUOVSK2xN0PVcppI6ObciIwH7DH3zdqxv27uOB/Zpn88ajGbDvjr6HEYNLDpQecxmY+RiZU/dWOd9qJlBL3Ffau57qDTVUAOrzEEsICoaaJqpYsXe4sGGi0k3DRIHoLS9QFbP+IuJbmE25zkiW2t89DuiAp"
    }
  }
}
